### ISSUE TITLE
Error while installing on macOS 10.14.1

### ISSUE THREAD

**Issue by TheBlueKingLP** [breeswish/express-minify#57]
I got the following error(s) when I try to install it.

`Administrators-MacBook-Pro:myproject administrator$ npm install express-minify
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated formatio@1.0.2: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> node-sass@0.9.6 install /Users/administrator/Downloads/myproject/node_modules/express-minify/node_modules/node-sass
> node build.js

(node:23746) [DEP0006] DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
  CXX(target) Release/obj.target/binding/binding.o
In file included from ../binding.cpp:1:
../../nan/nan.h:79:32: warning: 'BooleanValue' is deprecated [-Wdeprecated-declarations]
      || optionsObj->Get(opt)->BooleanValue();
                               ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2474:3: note: 'BooleanValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", bool BooleanValue() const);
  ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../binding.cpp:1:
../../nan/nan.h:83:32: warning: 'BooleanValue' is deprecated [-Wdeprecated-declarations]
      && optionsObj->Get(opt)->BooleanValue();
                               ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2474:3: note: 'BooleanValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", bool BooleanValue() const);
  ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../binding.cpp:1:
../../nan/nan.h:102:31: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
      ? optionsObj->Get(opt)->Uint32Value()
                              ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../binding.cpp:1:
../../nan/nan.h:189:68: error: too many arguments to function call, expected at most 2, have 4
    return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
           ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:6137:3: note: 'New' declared here
  static Local<Signature> New(
  ^
In file included from ../binding.cpp:1:
../../nan/nan.h:244:32: error: no member named 'CompileUnbound' in 'v8::ScriptCompiler'
    return v8::ScriptCompiler::CompileUnbound(
           ~~~~~~~~~~~~~~~~~~~~^
../../nan/nan.h:253:32: error: no member named 'CompileUnbound' in 'v8::ScriptCompiler'
    return v8::ScriptCompiler::CompileUnbound(
           ~~~~~~~~~~~~~~~~~~~~^
../../nan/nan.h:259:40: error: too few arguments to function call, expected 2, have 1
    return v8::BooleanObject::New(value).As<v8::BooleanObject>();
           ~~~~~~~~~~~~~~~~~~~~~~      ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:5035:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, bool value);
  ^
In file included from ../binding.cpp:1:
../../nan/nan.h:259:62: error: expected '(' for function-style cast or type construction
    return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                            ~~~~~~~~~~~~~~~~~^
../../nan/nan.h:259:64: error: expected expression
    return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                                               ^
../../nan/nan.h:266:30: warning: 'New' is deprecated [-Wdeprecated-declarations]
    return v8::StringObject::New(value).As<v8::StringObject>();
                             ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:5052:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../binding.cpp:1:
../../nan/nan.h:271:3: error: redefinition of 'NanNew'
  NanNew<v8::StringObject, v8::Handle<v8::String> >(
  ^
../../nan/nan.h:264:3: note: previous definition is here
  NanNew<v8::StringObject, v8::Local<v8::String> >(
  ^
../../nan/nan.h:273:30: warning: 'New' is deprecated [-Wdeprecated-declarations]
    return v8::StringObject::New(value).As<v8::StringObject>();
                             ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:5052:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../binding.cpp:1:
../../nan/nan.h:285:24: warning: 'New' is deprecated [-Wdeprecated-declarations]
    return v8::RegExp::New(pattern, flags);
                       ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:5109:10: note: 'New' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../binding.cpp:1:
../../nan/nan.h:289:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:283:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:291:24: warning: 'New' is deprecated [-Wdeprecated-declarations]
    return v8::RegExp::New(pattern, flags);
                       ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:5109:10: note: 'New' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../binding.cpp:1:
../../nan/nan.h:297:24: warning: 'New' is deprecated [-Wdeprecated-declarations]
    return v8::RegExp::New(pattern, flags);
                       ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:5109:10: note: 'New' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../binding.cpp:1:
../../nan/nan.h:301:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:295:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:303:24: warning: 'New' is deprecated [-Wdeprecated-declarations]
    return v8::RegExp::New(pattern, flags);
                       ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:5109:10: note: 'New' has been explicitly marked deprecated here
  static V8_DEPRECATED("Use maybe version",
         ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../binding.cpp:1:
../../nan/nan.h:309:51: error: too few arguments to function call, single argument 'context' was not specified
        v8::Isolate::GetCurrent(), val)->ToUint32();
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2435:3: note: 'ToUint32' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
  ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../binding.cpp:1:
../../nan/nan.h:315:51: error: too few arguments to function call, single argument 'context' was not specified
        v8::Isolate::GetCurrent(), val)->ToUint32();
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2435:3: note: 'ToUint32' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
  ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../binding.cpp:1:
../../nan/nan.h:320:60: error: no matching member function for call to 'ToInt32'
    return v8::Int32::New(v8::Isolate::GetCurrent(), val)->ToInt32();
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2437:43: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Int32> ToInt32(Local<Context> context) const;
                                          ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2450:30: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<Int32> ToInt32(Isolate* isolate) const);
                             ^
In file included from ../binding.cpp:1:
../../nan/nan.h:325:60: error: no matching member function for call to 'ToInt32'
    return v8::Int32::New(v8::Isolate::GetCurrent(), val)->ToInt32();
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2437:43: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Int32> ToInt32(Local<Context> context) const;
                                          ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2450:30: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<Int32> ToInt32(Isolate* isolate) const);
                             ^
In file included from ../binding.cpp:1:
../../nan/nan.h:368:9: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
      , v8::String::kNormalString
        ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2803:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../binding.cpp:1:
../../nan/nan.h:379:9: error: cannot initialize a parameter of type 'v8::NewStringType' with an rvalue of type 'v8::String::NewStringType'
      , v8::String::kNormalString
        ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2803:64: note: passing argument to parameter 'type' here
      Isolate* isolate, const uint8_t* data, v8::NewStringType type,
                                                               ^
In file included from ../binding.cpp:1:
../../nan/nan.h:385:69: error: too few arguments to function call, expected at least 3, have 2
    return v8::String::NewFromOneByte(v8::Isolate::GetCurrent(), arg);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~                               ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2802:3: note: 'NewFromOneByte' declared here
  static V8_WARN_UNUSED_RESULT MaybeLocal<String> NewFromOneByte(
  ^
In file included from ../binding.cpp:1:
../../nan/nan.h:391:69: error: too few arguments to function call, expected at least 3, have 2
    return v8::String::NewFromOneByte(v8::Isolate::GetCurrent(), arg);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~                               ^
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2802:3: note: 'NewFromOneByte' declared here
  static V8_WARN_UNUSED_RESULT MaybeLocal<String> NewFromOneByte(
  ^
In file included from ../binding.cpp:1:
../../nan/nan.h:477:63: error: cannot initialize a parameter of type 'v8::String::ExternalOneByteStringResource *' with an lvalue of type 'v8::String::ExternalStringResource *'
    return v8::String::NewExternal(v8::Isolate::GetCurrent(), resource);
                                                              ^~~~~~~~
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2862:64: note: passing argument to parameter 'resource' here
                                ExternalOneByteStringResource* resource));
                                                               ^
In file included from ../binding.cpp:1:
../../nan/nan.h:481:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/administrator/.node-gyp/10.14.1/include/node/v8.h:2710:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
9 warnings and 20 errors generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/administrator/Downloads/myproject/node_modules/express-minify/node_modules/node-sass
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed
npm WARN node-sass-middleware@0.3.1 requires a peer of node-sass@0.9.x but none is installed. You must install peer dependencies yourself.
npm WARN myproject@0.0.0 No repository field.
npm WARN myproject@0.0.0 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.9.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/administrator/.npm/_logs/2018-12-09T14_26_40_983Z-debug.log`

**Comment by Martii** [comment]
Looks like some of these come from developer dependency issues e.g. not in production environments.

**Comment by breezewish** [comment]
I suspect that this package is using a old node-sass which is not compatible with your node version. I will update it.
